//
//  DictionariesTableViewController.swift
//  Your Vocabulary
//
//  Created by Dmitrii Semykin on 4/01/18.
//  Copyright © 2018 Dmitrii Semykin. All rights reserved.
//

import UIKit
import CoreData

class DictionariesTableViewController: UITableViewController {

    // MARK: - Vars, lets, Outlets...
    
    var dictionaries = [Dictionary]()
    
    // MARK: - IBActions
    
    @IBAction func addNewDictionaryIntoTable(_ sender: UIBarButtonItem) {
        
        if let appDelegate = UIApplication.shared.delegate as? AppDelegate {
            let context = appDelegate.persistentContainer.viewContext
            if let entity = NSEntityDescription.entity(forEntityName: "Dictionaries", in: context) {
                let newDictionary = NSManagedObject(entity: entity, insertInto: context)
                newDictionary.setValue("New dictionary", forKey: "name")
                newDictionary.setValue(4, forKey: "countOfWords")
                
                do {
                    try context.save()
                } catch {
                    print("Failed saving")
                }
            }
        }
        
        
        tableView.reloadData()
    }
    
    // MARK: - Autogenerated controler methods
    
    override func viewDidLoad() {
        super.viewDidLoad()

        navigationController?.navigationBar.prefersLargeTitles = true
        
        if let appDelegate = UIApplication.shared.delegate as? AppDelegate {
            let context = appDelegate.persistentContainer.viewContext
            let request = NSFetchRequest<NSFetchRequestResult>(entityName: "Dictionaries")
            
            request.returnsObjectsAsFaults = false
            
            do {
                let result = try context.fetch(request)
                    
                for data in result as! [NSManagedObject] {
                    var tmp_dic = Dictionary(data.value(forKey: "name") as! String)
                    tmp_dic.countOfWords = Int(data.value(forKey: "countOfWords") as! Int32)
                    dictionaries += [tmp_dic]
                }
            } catch {
                print("Failed fetching")
            }
        }
        
        // Uncomment the following line to preserve selection between presentations
        // self.clearsSelectionOnViewWillAppear = false

        // Uncomment the following line to display an Edit button in the navigation bar for this view controller.
        // self.navigationItem.rightBarButtonItem = self.editButtonItem
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    // MARK: - Table view data source

    override func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return dictionaries.count
    }

    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "StandartDictionaryCell", for: indexPath)

        // Configure the cell...
        
        cell.textLabel?.text = dictionaries[indexPath.row].name
        cell.detailTextLabel?.text = "Count of words :\(dictionaries[indexPath.row].countOfWords)"

        return cell
    }

    /*
    // Override to support conditional editing of the table view.
    override func tableView(_ tableView: UITableView, canEditRowAt indexPath: IndexPath) -> Bool {
        // Return false if you do not want the specified item to be editable.
        return true
    }
    */

    // Override to support editing the table view.
    override func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCellEditingStyle, forRowAt indexPath: IndexPath) {
        if editingStyle == .delete {
            // Delete the row from the data source
            dictionaries.remove(at: indexPath.row)
            tableView.deleteRows(at: [indexPath], with: .fade)
        } else if editingStyle == .insert {
            // Create a new instance of the appropriate class, insert it into the array, and add a new row to the table view
        }    
    }

    /*
    // Override to support rearranging the table view.
    override func tableView(_ tableView: UITableView, moveRowAt fromIndexPath: IndexPath, to: IndexPath) {

    }
    */

    /*
    // Override to support conditional rearranging of the table view.
    override func tableView(_ tableView: UITableView, canMoveRowAt indexPath: IndexPath) -> Bool {
        // Return false if you do not want the item to be re-orderable.
        return true
    }
    */

    
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        switch segue.identifier {
        case "dictionarySegue"?:
            if let cell = sender as? UITableViewCell {
                if let wtvc = segue.destination as? WordsTableViewController {
                    if let indexPath = tableView.indexPath(for: cell) {
//                        wtvc.dictionaryName = dictionaries[indexPath.row].name
//                        wtvc.words = dictionaries[indexPath.row].words
                    }
                }
            }
        default:
            break
        }
    }

}
