//
//  WordViewController.swift
//  Your Vocabulary
//
//  Created by Dmitrii Semykin on 5/01/18.
//  Copyright © 2018 Dmitrii Semykin. All rights reserved.
//

import UIKit

class WordViewController: UIViewController {
    
    // MARK: - Vars, lets, Outlets...
    
    private let wordMark: [String:Int] = ["Word" : 0,
                                          "Translation" : 1,
                                          "Definition" : 2,
                                          "ExtraInfo" : 3,
                                          "Synonym" : 4,
                                          "Example" : 5]
    
    @IBOutlet var wordFields: [UITextField]!
    
    var currentDictionary: Dictionary?
    
    var word: Word?
    
    @IBAction func saveWord(_ sender: UIButton) {
        if (wordFields[wordMark["Word"]!].text?.isEmpty)! {
            if (wordFields[wordMark["Translation"]!].text?.isEmpty)! {
                if word != nil {
                    
                }
            }
        }
    }
    
    // MARK: - IBActions
    
    // MARK: - Autogenerated controler methods
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        navigationItem.largeTitleDisplayMode = .never
        
        if let tmp_word = word {
            wordFields[wordMark["Word"]!].text = tmp_word.word
            navigationItem.title = tmp_word.word
            
            if let trans = tmp_word.translation {
                wordFields[wordMark["Translation"]!].text = trans
            }
            
            if let def = tmp_word.definition {
                wordFields[wordMark["Definition"]!].text = def
            }
            
            if let extraInfo = tmp_word.extraInfo {
                wordFields[wordMark["ExtraInformation"]!].text = extraInfo
            }
            
            if let synonym = tmp_word.synonym {
                wordFields[wordMark["Synonym"]!].text = synonym
            }
            
            if let example = tmp_word.example {
                wordFields[wordMark["Example"]!].text = example
            }
        }
        
        // Do any additional setup after loading the view.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destinationViewController.
        // Pass the selected object to the new view controller.
    }
    */

}
